image: python:3.7

options:
  max-time: 20

pipelines:
  custom: # manully triggered
    tests:
    - step:
        name: Download and test
        caches:
          - venv
          - corpus-and-model
        script:
          - source tests/get_env.sh
          - source venv/bin/activate && python -m unittest discover tests/

definitions:
  caches:
    venv: venv
    corpus-and-model: tests/data
