image: python:3.7


options:
  max-time: 20

pipelines:

  custom: # manully triggered
    download:
    - step:
        name: Download
        caches:
          - pip
          - googlenews-magnitude
          - test7-bin
          - test7-gz
          - test7-magnitude
        script:
          - pwd

    test:
    - step:
        name: Test
        caches:
          - pip
          - googlenews-magnitude
          - test7-bin
          - test7-gz
          - test7-magnitude
        script:
          - pwd

  pull-requests: # automatically triggered
    '**': #this runs as default for any branch not elsewhere defined
    - step:
        caches:
          - pip
          - googlenews-magnitude
          - test7-bin
          - test7-gz
          - test7-magnitude
        name: Testing
        script:
          - pwd

definitions:
  caches:
    googlenews-magnitude: tests/GoogleNews-vectors-negative300.magnitude
    test7-bin: tests/text7.head.bin
    test7-gz: tests/text7.head.gz
    test7-magnitude: tests/text7.head.magnitude.gz
