image: python:3.7


options:
  max-time: 20

pipelines:

  custom: # manully triggered
    download:
    - step:
        name: Download
        caches:
          - pip
          - googlenews-magnitude
          - test7-bin
          - test7-gz
          - test7-magnitude
        script:
          - pip install -r requirements.txt
          - wget --quiet http://magnitude.plasticity.ai/word2vec/light/GoogleNews-vectors-negative300.magnitude -O GoogleNews-vectors-negative300.magnitude
          - mv GoogleNews-vectors-negative300.magnitude tests/GoogleNews-vectors-negative300.magnitude
          - ls tests/
          - source tests/get_corpus_and_model.sh
    test:
    - step:
        name: Test
        caches:
          - pip
          - googlenews-magnitude
          - test7-bin
          - test7-gz
          - test7-magnitude
        script:
          - pip install -r requirements.txt
          - wget --quiet http://magnitude.plasticity.ai/word2vec/light/GoogleNews-vectors-negative300.magnitude -O GoogleNews-vectors-negative300.magnitude
          - mv GoogleNews-vectors-negative300.magnitude tests/GoogleNews-vectors-negative300.magnitude
          - ls tests/
          - source tests/get_corpus_and_model.sh
          - python -m unittest discover tests/

  pull-requests: # automatically triggered
    '**': #this runs as default for any branch not elsewhere defined
    - step:
        caches:
          - pip
          - googlenews-magnitude
          - test7-bin
          - test7-gz
          - test7-magnitude
        name: Testing
        script:
          - pip install -r requirements.txt
          - wget --quiet http://magnitude.plasticity.ai/word2vec/light/GoogleNews-vectors-negative300.magnitude -O GoogleNews-vectors-negative300.magnitude
          - mv GoogleNews-vectors-negative300.magnitude tests/GoogleNews-vectors-negative300.magnitude
          - ls tests/
          - source tests/get_corpus_and_model.sh
          - python -m unittest discover tests/

definitions:
  caches:
    googlenews-magnitude: tests/GoogleNews-vectors-negative300.magnitude
    test7-bin: tests/text7.head.bin
    test7-gz: tests/text7.head.gz
    test7-magnitude: tests/text7.head.magnitude.gz
