image: python:3.7


options:
  max-time: 20

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - tests/GoogleNews-vectors-negative300.heavy.magnitude
  - tests/text7.head.bin
  - tests/text7.head.gz
  - tests/text7.head.magnitude.gz

before_script:
    - wget --quiet http://magnitude.plasticity.ai/word2vec/heavy/GoogleNews-vectors-negative300.magnitude -O tests/GoogleNews-vectors-negative300.heavy.magnitude
    - source tests/get_corpus_and_model.sh

pipelines:

  custom: # manully triggered
    - step:
        name: Testing
        script:
          - python -m unittest discover tests/

  pull-requests: # automatically triggered
    '**': #this runs as default for any branch not elsewhere defined
    - step:
        name: Testing
        script:
          - python -m unittest discover tests/
